name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: go env -w GO111MODULE=on
      - run: go mod download golang.org/x/sync
      - run: CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags '-extldflags "-static"' -o dist/bot cmd/tg-bot/tg-bot-service.go
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dta-secret-santa"
          heroku_email: "admin@digital-technology.agency"
          healthcheck: "https://dta-secret-santa.herokuapp.com/health"
          appdir: "dist/bot"
